language: ruby
rvm:
  - 2.2.3
before_install:
  - rvm install 2.2.3
install:
  - bundle install --path vendor/bundle
script:
  - git config --global user.name 'kjhnns'
  - git config --global user.email 'joh.klumpe@gmail.com'
  - git remote set-url origin https://dentist-huels:${GH_TOKEN}@github.com/dentist-huels/dentist-huels.github.io.git
  - bundle exec middleman build
  - bundle exec middleman deploy
branches:
  only:
  - master
